config/routes.rb
Rails.application.routes.draw do
  
  resources :user_projects
  resources :artifacts
  resources :tenants do
    resources :projects do
      get 'users', on: :member
      put 'add_user', on: :member
    end
  end
  
  
  resources :members
  get 'home/index'

  root :to => "home#index"

    
  as :user do   
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, :controllers => { 
    :registrations => "registrations",
    :confirmations => "confirmations",
    :sessions => "milia/sessions", 
    :passwords => "milia/passwords", 
  }
  
  match 'plan/edit' => 'tenants#edit', via: :get, as: :edit_plan
  match 'plan/update' => 'tenants#update', via: [:put, :patch], as: :update_plan

end

app/models/artifact.rb
class Artifact < ActiveRecord::Base
  belongs_to :project
end

app/controllers/artifacts_controller.rb
class ArtifactsController < ApplicationController
  before_action :set_artifact, only: [:show, :edit, :update, :destroy]

  # GET /artifacts
  # GET /artifacts.json
  def index
    @artifacts = Artifact.all
  end

  # GET /artifacts/1
  # GET /artifacts/1.json
  def show
  end

  # GET /artifacts/new
  def new
    @artifact = Artifact.new
    @artifact.project_id = params[:project_id]
  end

  # GET /artifacts/1/edit
  def edit
  end

  # POST /artifacts
  # POST /artifacts.json
  def create
    @artifact = Artifact.new(artifact_params)

    respond_to do |format|
      if @artifact.save
        format.html { redirect_to @artifact, notice: 'Artifact was successfully created.' }
        format.json { render :show, status: :created, location: @artifact }
      else
        format.html { render :new }
        format.json { render json: @artifact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artifacts/1
  # PATCH/PUT /artifacts/1.json
  def update
    respond_to do |format|
      if @artifact.update(artifact_params)
        format.html { redirect_to @artifact, notice: 'Artifact was successfully updated.' }
        format.json { render :show, status: :ok, location: @artifact }
      else
        format.html { render :edit }
        format.json { render json: @artifact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artifacts/1
  # DELETE /artifacts/1.json
  def destroy
    @artifact.destroy
    respond_to do |format|
      format.html { redirect_to artifacts_url, notice: 'Artifact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artifact
      @artifact = Artifact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artifact_params
      params.require(:artifact).permit(:name, :key, :project_id)
    end
end

app/helpers/artifacts_helper.rb
module ArtifactsHelper
end

app/views/artifacts/_form.html.erb
<%= form_for(@artifact) do |f| %>
  <% if @artifact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artifact.errors.count, "error") %> prohibited this artifact from being saved:</h2>

      <ul>
      <% @artifact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :doc, value: "File to upload", :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.file_field :doc, class: "form-control" %>
    </div>
  </div>
  <%= f.hidden_field :project_id %>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tenant_project_path(tenant_id: Tenant.current_tenant_id, id: @artifact.project_id), :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/artifacts/_list.html.erb
<%- model_class = Artifact -%>
<table class="table table-striped">
    <thead>
        <tr>
            <th><%= model_class.human_attribute_name(:name) %></th>
            <th><%= model_class.human_attribute_name(:key) %></th>
            <th><%=t '.actions', :default => t("helpers.actions") %></th>
        </tr>    
    </thead>
    <tbody>
        <% artifacts.each do |artifact| %>
            <tr>
                <td><%= link_to artifact.name, artifact_path(artifact), class: "main-link" %></td>    
            </tr>
        <%end%>
    </tbody>
</table>
<% if @project %>
    <%= link_to "New Artifact", new_artifact_path(project_id: @project.id), :class => 'btn btn-primary' %>
<%end%>

app/views/artifacts/edit.html.erb
<%- model_class = Artefact -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/artifacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Artifacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Key</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artifacts.each do |artifact| %>
      <tr>
        <td><%= artifact.name %></td>
        <td><%= artifact.key %></td>
        <td><%= artifact.project %></td>
        <td><%= link_to 'Show', artifact %></td>
        <td><%= link_to 'Edit', edit_artifact_path(artifact) %></td>
        <td><%= link_to 'Destroy', artifact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artifact', new_artifact_path %>

app/views/artifacts/new.html.erb
<h1>New Artifact</h1>

<%= render 'form' %>

<%= link_to 'Back', artifacts_path %>

app/views/artifacts/show.html.erb
<div align="center">
  <%- model_class = Artifact -%>
  <div class="page-header">
    <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
  </div>
</div>

<dl class="dl-horizontal col-md-offset-4">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @artifact.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:key) %>:</strong></dt>
  <dd><%= @artifact.key %></dd>
  <dt><strong><%= model_class.human_attribute_name(:project_id) %>:</strong></dt>
  <dd><%= @artifact.project_id %></dd>
</dl>

<div align="center">
  <div>
    <iframe></iframe>
  </div>
  <%= link_to "Download", @artifact.doc.url, :class => 'btn btn-default' %>
</div>